#include "interrupt.h"

float offset1;
float offset2;

#define ENABLE_SYSTICKBIT    1
float overflow=0;



void Enable_SYSTICK_Interrupt()
{
SETBIT(REG(SYSTICK_BASE+SYSTICK_CTRL),ENABLE_SYSTICKBIT);
}


void Disable_SYSTICK_Interrupt()
{
CLRBIT(REG(SYSTICK_BASE+SYSTICK_CTRL),ENABLE_SYSTICKBIT);
}

void SysTick_Handler ()	
{
	overflow++;
}










void ENABLE_EXTERNAL_INTERRUPT_PORTF()//ENABLE BIT 0,4
{
	
		SETBIT(REG(0xE000E100),30);  //NVIC->ISER[0] |= (1<<30);/*Enable the interrupt of GPIO_PORTF that is the bit30 in ISER [0] dont forget every ISER has 31 interrupt so the sum is 124 interrupt*/
	//NVIC->IP[30] |= 3<<5;/*make the proirity of GPIO_PORTF equal to 3*/
	
	SETBIT(GPIO_PORTF_IM,0); 	/*SETBI IN INTERRUPT MASK TO MAKE IT AS INTERRUT PIN*/
	SETBIT(GPIO_PORTF_IM,4);	/*SETBI IN INTERRUPT MASK TO MAKE IT AS INTERRUT PIN*/
	CLRBIT(GPIO_PORTF_IS,0);  /*CLEARING THE BIT TO BE EDGE TRIGERED OF U WANT TO MAKE IT LEVEL SENSETIVE USE SETBIT*/
	CLRBIT(GPIO_PORTF_IS,4);	/*CLEARING THE BIT TO BE EDGE TRIGERED OF U WANT TO MAKE IT LEVEL SENSETIVE USE SETBIT*/
	
	CLRBIT(GPIO_PORTF_IEV,0); /*CLEARING THE BIT TO MAKE IT FALLING EDGE TRIGGERED*/
	CLRBIT(GPIO_PORTF_IEV,4);	/*CLEARING THE BIT TO MAKE IT FALLING EDGE TRIGGERED*/
	
	SETBIT(GPIO_PORTF_ICR,0); /*CLEARING THE INTERRUPT FLAG THAT HAS BEEN RISEN AFTER INTERRUPT IN THE START OF PROGRAM*/
	SETBIT(GPIO_PORTF_ICR,4); /*CLEARING THE INTERRUPT FLAG THAT HAS BEEN RISEN AFTER INTERRUPT IN THE START OF PROGRAM*/
}


